name: Deploy on Github

on:
  release:
    types: [published]

permissions:
  actions: read
  contents: write
  id-token: write

jobs:
  eliza:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Eliza Notary
        uses: zktx-io/eliza-notary@main
        with:
          project-path: './my_first_package'
          report-path: './audit-report'
          force-audit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

  build:
    needs: eliza
    uses: zktx-io/slsa-on-sui/.github/workflows/generator_generic_slsa3.yml@main
    with:
      move-directory: "my_first_package"
